feat: Adding docs for new `ProverClient` and `groth16` and `compressed` mode (#627)
Co-authored-by: Chris Tian <chris@succinct.xyz>

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -1,11 +1,13 @@
 SHELL := /bin/bash
+.SHELLFLAGS = -e
 
 all:
 	@set -e; \
 	for dir in */ ; do \
 		if [ -d "$${dir}program" ]; then \
 			echo "Building in $${dir}program..."; \
-			cd $${dir}program && cargo clean && cargo update && cargo prove build && cd ../../; \
+			cd $${dir}program && cargo prove build || { echo "Failed at command: cd $${dir}program && cargo prove build"; exit 1; }; \
+			cd ../../; \
 		else \
 			echo "No program directory in $${dir}, skipping..."; \
 		fi; \
